pipeline {
    agent any
    tools {
        // Set up any tools that you need to build your project
    }
    stages {
        stage('Build') {
            steps {
                // Configure the Git plugin to check out the repository
                git branch: 'master', url: 'https://github.com/iestarks/python.git'
                
                // Run any build steps that you need
                sh 'mvn clean install'
            }
        }
    }
    // Enable triggering on push events to the master branch
    triggers {
        githubPush(branchFilter: 'main')
    }
}
